import type { Metadata } from "next";
import Auth from "@/components/auth/auth";
import { Toaster } from "@/components/ui/toaster";
import { ShapeProvider } from "@/Context/shapeContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Auth>
            <ShapeProvider>
            {children}
            </ShapeProvider>
          <Toaster />

        </Auth>
      </body>
    </html>
  );
}
