import type { Metadata } from "next";
import "./globals.css";
import Auth from "@/components/auth/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Auth>
          
          {children}

        </Auth>
      </body>
    </html>
  );
}
