import type { Metadata } from "next";
import "./globals.css";
import Auth from "@/components/auth/auth";
import NavBar from "@/components/Navbar/Navbar";
import { isAuthenticated } from "@/utils/amplify-utils";
import { Toaster } from "@/components/ui/toaster";
import { ShapeProvider } from '@/Context/shapeContext';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <NavBar isSignedIn={await isAuthenticated()} /> */}
        <Auth>
          
          <ShapeProvider>
            {children}
          </ShapeProvider>
          <Toaster />

        </Auth>
      </body>
    </html>
  );
}
